### ISSUE TITLE
Vault Integrity

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#10]
A user can is only allows to access the content of a secret bundle if and only if they can have the ability to decrypt everything inside a secret bundle. This is because a secret bundle is the unit of sharing.

Merkle trees have the property that if a key can decrypt a node in the tree, it can also decrypt all subsequent children of that node. Thus, is a user can decrypt the root node of merkle tree which represent a secret bundle then they are able to decrypt the entire secret bundle and can then be granted access to that bundle.

**Comment by CMCDragonkai** [comment]
Merkle trees don't directly have to do with encryption, more hashing. We need to find out how to apply it to a directory structure first.

**Comment by CMCDragonkai** [comment]
js-encryptedfs https://github.com/MatrixAI/js-encryptedfs/issues/11 already deals with chunk and file integrity. This is sort of about maintaining integrity of the whole vault. So one should be able to detect whether any part of the vault is corrupted before any kind of access to the vault. This includes the OP's comment about not being able the decrypt any part of the vault, if one part of the vault is not decryptable for some reason. However I'm not sure how complicated this can be, so I think it's low priority.

The reason why this could be complicated is because you want this integrity check to be O(1) basically, but how is that possible!?

**Comment by CMCDragonkai** [comment]
Seems like it is possible considering that ZFS does this as well: https://superuser.com/questions/351079/why-is-zfs-stored-in-a-tree-structure

**Comment by robert-cronin** [comment]
Vaults now have chunk level-integrity guarantees via the AES-GCM algorithm.

**Comment by CMCDragonkai** [comment]
Does this mean this issue is resolved?

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
