### ISSUE TITLE
Implement a gRPC Stream Channel for Polykey Events to the Frontend

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#137]
To implement some kind of Pessimistic Concurrency Control, we need to have a gRPC stream that can be subscribed to by the frontend (either CLI REPL or GUI) that tell the front end if any changes happen in a server-push kind of way

**Comment by CMCDragonkai** [comment]
This isn't PCC. This is just a matter of streaming events to the frontend so it can be eventually consistent and have near-realtime synchronization of UI state.

The CC hasn't come into play yet. It's when you actually have possible ambiguities or write conflicts that's when CC comes into play.

@gideonairex We will need this for both cross-client interaction and KN to KN interaction. So the same infrastructure must be used.

@robert-cronin Please provide design diagrams for implementing a GRPC channel stream. And are we then using JSON messages in this case? Or I guess protobuf messages will become JSON as well.

These events will require a schema design. Please propose a well-typed schema design for these kinds of messages.

If we take the idea of redux/vue forward, it make sense for these message to have a similar payload format, since they will result in vuex dispatched actions.

**Comment by CMCDragonkai** [comment]
Also while we might have been using Req/Rep GRPC calls, this is about the server calling the client now. But our clients establish this streaming connection. But think of the server calling the client. Perhaps GRPC has a way of hooking in client callbacks for the server to be calling? The server is the KN in this case.

**Comment by CMCDragonkai** [comment]
Will be good practice for Convergence UI.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
