### ISSUE TITLE
Automatic Commits for Vault Changes

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#16]
Changes to any vault should involve an automatic commit to our Git version control system.

We should try to make this system write sensible messages. And we need to carefully manage the Git commit history and consider issues like diverging histories and merge strategies dealing with incompatible histories. We need to make this as automatic as possible so that end-users do not have to do a manual merge like they would for source control.

Issue regarding redundant commit messages: https://github.com/MatrixAI/js-polykey/issues/5 - we may need to be able to transactionally modify things. So edits to multiple files should be 1 commit if they represent the same change in secrets.

Initial experiment here: https://github.com/MatrixAI/js-polykey/commit/aa8d4aeac26477a71c8cdd15bc420c06ee9ad51f

**Comment by robert-cronin** [comment]
Automatic commits will be implemented in the upcoming PR #43, however they still do not address the case of multiple files changed at once since polykey simply does not allow one to modify multiple secrets at once. A commit is made for every action currently possible (`addSecret`, `removeSecret` and `updateSecret` which I have added as a part of the PR)
