### ISSUE TITLE
Vaults should be able to handle hidden files

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#196]
Polykey vaults should treat hidden files like any other file.

Hidden files are files that have `.` in front of their name.

When viewing the files in our GUI/CLI, it should show hidden files just like any other file.

From PK, we give no special treatment to hidden files.

To test conformance with this, please create a test for our vaults that involve CRUD of hidden files, or files with `.` in front of their name.

Include hidden directories as well.

Previous issue with additional context: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/issues/161

1. Create CRUD tests for hidden files for Vaults
2. Create CRUD tests for hidden directories for Vaults

**Comment by scottmmorris** [comment]
There are no tests for this but I believe polykey should handle hidden files in this way regardless.

I will create some tests in the agent MR that:

- Add a hidden file/directory
- Get contents from a hidden file/directory
- Change contents in a hidden file/directory
- Delete a hidden file/directory

**Comment by scottmmorris** [comment]
So it turns out this wasn't the case for directories but it was simple to rework this.

The question is does this also apply outside the context of Polykey? For example if the user specifies a directory of secrets to add on their disk, are the hidden files there added in as well?

I'm not sure if you had something in mind @CMCDragonkai but my thoughts would be if you are adding a directory of secrets then directory is generally a collection of things that should stay together and so the hidden files should come with the directory. This is how I've implemented it for the moment

**Comment by CMCDragonkai** [comment]
Yes hidden files should be maintained and copied in as well.
