### ISSUE TITLE
Stealth mode feature.

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#199]
There may be a need for a stealth mode feature for Polykey But it is not currently MVP.
I'm not sure that stealth mode would do. It might just tell the current node to show as offline. @CMCDragonkai could you add any more details?

**Comment by CMCDragonkai** [comment]
Check the polykey-design issues, is stealth mode mentioned there?

**Comment by tegefaulkes** [comment]
I can't find anything in the design issues. there is src-old/nodes/NodeManager.ts:179 in the old code.

**Comment by joshuakarp** [comment]
There's a comment about it here: https://gitlab.com/MatrixAI/Engineering/Polykey/polykey-design/-/issues/31#note_495622490. This is the only further information I could find.

**Comment by CMCDragonkai** [comment]
I believe the stealth mode was to prevent it from being discovered. Right now the only kind of node discovery we have is through Kademlia. So stealth would just mean the node does not respond or participate in the Kademlia process.

Additionally due to MatrixAI/js-mdns#1, stealth mode would also mean the node does not respond to LAN multicast discovery.

I'm not sure if it should also ignore scan/ping/keepalive. I reckon direct connections should still occur. But this requires a UI/UX review.

**Comment by CMCDragonkai** [comment]
Going to cancel this, as this doesn't really fit within the rest of the PK design now. In fact with authenticated networks and network segregation @amydevs it stealth mode would simply mean not connecting to any of the named networks - and therefore the networking layer would just reject connections.
