### ISSUE TITLE
Git backed server for sharing vaults

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#31]
TBD.

Should be lower level pull/push style.

However we can also have a higher level sync. But that can also be automated via the polykey agent.

Relevant to MatrixAI/PolyKey#31

**Comment by robert-cronin** [comment]
What is the difference between this issue and #8 ? I think we should close this one

**Comment by robert-cronin** [comment]
As was discussed in #32, isomorphic-git does not yet have server like functions, we have have created our own backend git server over http by stitching together code from [node-git-server](https://github.com/gabrielcsapo/node-git-server) and the [http-receiver](https://github.com/isomorphic-git/isomorphic-git/tree/http-receiver) branch of isomorphic-git.
The key thing missing was the uploadPack functionality, node-git-server gave a lovely example of how to setup the git http backend using the CLI, but we needed it to be fully contained within JavaScript so I went ahead and built a server using the components on the http-receiver branch. 

I think isomorphic-git is heading in the direction of allowing server like functionality, but I can't be certain of when as the branch and relevant issues haven't been worked on for some time. If it ever does come around, we would probably want to use it instead of our custom code.

As for now, the `uploadPack` (i.e. simple clone and pull) is working, but there is still some work to do in order to get `receivePack` (i.e. push) working. Isogit also has some great code already developed for receivePack and we can take some inspiration from there.
