### ISSUE TITLE
Peer to Peer Architecture

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#32]
Inspirations:

* https://github.com/sit-fyi/sit
* Dat P2P
* Libp2p (js libraries available)
* Kademlia

The peer to peer architecture is the architecture in which Polykey Keynodes can discover each other and connect to each other. Note that communication between Polykey keynodes happens over this p2p network. But social discovery occurs via social providers like Keybase which facilitate discovery of human profiles to automated keynodes.

**Comment by robert-cronin** [comment]
For p2p architecture and sharing vaults, its possible to do it in 2 ways using existing libraries:
- using [libp2p](https://github.com/libp2p/js-libp2p) to setup a tcp connection between two polykey nodes and somehow exposing the git repository via a http connection over the tcp connection.
- using [IPFS](https://github.com/ipfs/js-ipfs) to setup a http gateway and share a bare git repo for pulling on node B every time node A asks for it. Then isomorphic-git can just use the standard node http object to make a pull request on the address and port of node B.

Both of the above are not always 100% debuggable and we have little to no control over the implentation of these two. So it is worth looking into building our own p2p architecture from scratch. This would involve two phases:
1) Developing a tcp connection between nodes on a local network and serving a vault via isomorphic git. The tcp connection can be creating using the nodejs `net` module.
2) Developing a distributed hash table for peer and content discovery and possibly even a circuit relay to get around firewalls and nat layers (ipfs does something like this)

We can take some ideas from libp2p such as multiaddr and multihash and look into Kademlia for the DHT implementation. Here is the Kademlia paper: 
https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf
I will make notes on this as I enter phase 2.

**Comment by robert-cronin** [comment]
I managed to get a preliminary connection setup with inspiration from [node-git-server](https://github.com/gabrielcsapo/node-git-server). It basically acts as a node backend for  a git http server. The good thing about this is we can adapt it to use EFS to serve the git repo from upperDir (virtualfs).

The reason I had to go this far out is because isomorphic-git does not yet support server like functions: https://github.com/isomorphic-git/isomorphic-git/issues/464. Perhaps once it does, we can use the isogit implementation but I think we will want to tightly control this part of the p2p architecture anyway.

We will need to adapt it to a pure JavaScript implementation. I think this is possible, the main thing is looking at streams (for this there is [readable-stream](https://github.com/nodejs/readable-stream)) and http support (for this there is [axios](https://github.com/axios/axios))

**Comment by robert-cronin** [comment]
I have a multicast DNS peer discovery mechanism working now, all you need is the public key of the node you wish to connect to and the handshake occurs over UDP multicast address (`224.0.0.251:5353`).

The requesting node broadcasts a message encrypted with the target node's public key and thus is only decrypt-able by the target node. The message consists of some random bytes as well as the requesting nodes public key and address (`ip:port`)

Successful handshake occurs when the target node sends a return message back to the requesting node consisting of the decrypted random bytes and the address (`ip:port`) of the target node, then communications can be moved to the target nodes address. After the handshake, both nodes store each other's info as a new peer in their `peerStore`

The return message is re-encrypted with the requesting nodes public key so communications are always secure. I'm not sure if it needs to be this secure since its only the pubkey and address so perhaps its something we can reconsider down the line.

**Comment by robert-cronin** [comment]
Multicast Peer discovery was added in PR #40 and the git server/client is added for p2p vault sharing in PR #43
