### ISSUE TITLE
Social Discovery Network

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#33]
Related to MatrixAI/js-polykey#32 but instead focused on the human network instead of the machine network. Keybase now offers the ability for arbitrary services to become to integrate social identity proof to keybase: https://keybase.io/docs/proof_integration_guide

Other social networks may also be possible.

Also relevant discussion: https://news.ycombinator.com/item?id=19639297

**Comment by robert-cronin** [comment]
I think direct integration for signup/login is possible as well as for peer discovery.

For peer discovery, its quite simple to use keybase [lookup](https://keybase.io/docs/api/1.0/call/user/lookup) api. We can expose a function like `findSocialUser` that takes a `handle` like `robert-cronin` as well as a service like `github` and then queries the keybase network for the pubKey attached to that socially proven user. This is linking digital identities to social identities.

Direct integration can go further because keybase allows one to [signup](https://keybase.io/docs/api/1.0/call/signup) and [login](https://keybase.io/docs/api/1.0/call/login) all via a HTTP API, once you are authenticated and logged in, you can [fetch the keys](https://keybase.io/docs/api/1.0/call/key/fetch) needed to initialise PolyKey and then you have a PolyKey node directly linked to a socially proven human identity which solves the key sharing bootstrapping problem. 

Keybase integration for peer discovery will be implemented in the upcoming PR #40. After that, the user experience becomes quite smooth: user asks polykey to find `robert-cronin`, and then if the user's keynode is running on the same local area network (LAN), multicast peer discovery will find it and exchange peer information and vault sharing can proceed from there.

Integration for signup and login will have to be done on a later PR, there are still some things to figure out, such as if keybase actually releases the users private key over https or whether or not we should have a derived sub key for polykey operations and how to do that.

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
