### ISSUE TITLE
VaultInternal Version and Logging

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#336]
### Specification
Logging is similar to a git log. where we get the commit history tracing back from the specified ref or the `HEAD` if no ref specified. It should contain information relating to each commit ordered in newest to oldest. The information it contains is
- ref
- author information
- commit message containing a generated list of changes for each commit.

This history will be linear and only containing the commits from the `main` branch. Any commits outside the branch can not be listed.

We need to have a way to checkout previous history of the vault. this will be done via a Version command. To set the commit we wish to check out it should take a ref parameter that accepts `HEAD`, `main` or any valid ref string. We should for safety check if the specified ref exists within the expected branch. This should be unnecessary due to GC but it's any easy check to include.

Specify this out more if needed. Add details for command usage.

### Additional context
* Relates #266 
* From: https://github.com/MatrixAI/js-polykey/pull/266#issuecomment-1019427884
* To: https://github.com/MatrixAI/js-polykey/pull/266#issuecomment-1022066431

### Tasks

* [x] 1. create/update vault log command.
* [x] 2. create/update vault version command.

**Comment by tegefaulkes** [comment]
EDIT: moved comment to other issue https://github.com/MatrixAI/js-polykey/issues/335#issuecomment-1057515765

**Comment by CMCDragonkai** [comment]
Main reason to prefer the spec that I setup first is that the system is less complex when the roles of each component is "constant". That is they don't change due to different situations. One can say something like this:

1. Every time you make a change, whether that add new history or change old history, you always move the HEAD and branch pointer every time.
2. When you recover, you always recover from the branch pointer (because it is moved at the very end before dirty is flipped).

Finally in the future, if we allow multi-verse history, then branch pointers are always "linear paths" through the history graph. No such thing as a temporary branch pointer.
