### ISSUE TITLE
Introduce support for macOS CI/CD

### ISSUE THREAD

**Issue by joshuakarp** [MatrixAI/Polykey#425]
### Tasks

Currently in the process of participating in the macOS Build Cloud Runners beta https://gitlab.com/gitlab-com/macos-buildcloud-runners-beta

Queries and responses:

> 
> > Are we only able to have one project using the macOS Runner?
> 
> While we are not yet fully on the autoscaler, we are limiting access to one  project. Once we transition then there will be no limit.
> 
> > Can the CI/CD do a complete signed build for Mac App Store/iOS?
> 
> Yes this will work, however we need to document options for codesigning process in our initial documentation MR.  
> (Note from me: they provided instructions for how to set this up.)

**Comment by joshuakarp** [comment]
See also the following issue regarding Nix Build Pipelines with macOS: https://github.com/MatrixAI/TypeScript-Demo-Electron/issues/10

**Comment by joshuakarp** [comment]
@tegefaulkes @CMCDragonkai as a reminder for the macOS Build Cloud Runners.

For `js-polykey` on GitLab:

> Your macOS runner should now be available and should appear active in your Runner's list.
> 
> A very basic example to get you started:
> 
> ```yaml
> tags: [ shared-macos-amd64 ]
> image: macos-11-xcode-12 # https://docs.gitlab.com/ee/ci/runners/build_cloud/macos/environment.html
> job:
>   script:
>     - echo "hello world"
> ```

**Comment by CMCDragonkai** [comment]
This is being done in https://github.com/MatrixAI/js-polykey/pull/292. When that gets merged this issue can be closed.

So far only 1 project can this be applied to. This is the `js-polykey` project in: https://gitlab.com/MatrixAI/open-source/js-polykey.

Due to this issue: https://github.com/MatrixAI/Polykey/issues/5, we are going to be merging these 2 repos together. I think it will still work because the project allowed is filtered by a project ID or CI/CD ID right? So if we are just using `js-polykey` but just renaming the repo (including URL) it should all be fine.

**Comment by CMCDragonkai** [comment]
It seems like there's no 1 project limit mentioned in the README.md anymore. Perhaps we can ask for https://gitlab.com/MatrixAI/open-source/typescript-demo-lib as well?

**Comment by CMCDragonkai** [comment]
Added a new request for the other repos including our electron project: https://gitlab.com/gitlab-com/macos-buildcloud-runners-beta/-/issues/233
