### ISSUE TITLE
PolyKey Node as a Federated Hierarchy of Certificate Authorities (Federation of Trust)

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#48]
As an initial solution, polykey lib should implement an interface to allow arbitrary CA's to be used for PKI (related to https://github.com/MatrixAI/PolyKey/issues/25#issuecomment-651558297), however we also want to facilitate a 'web of trust' by allowing polykey nodes to act as certificate authorities.

**Comment by CMCDragonkai** [comment]
Web of trust is actually outside of the PKI infrastructure. It was designed to be an alternative to the hierarchical PKI system.

However bridging web of trust with PKI is like having federated hierarchies. So that's what polykey can do. Because Polykey agents act within a hierarchy (thus usable for a corporation or within your personal hierarchy of secrets), but at the same time the ability to share secrets with other human entities that don't exist within a hierarchy allows to federate with other networks.

Every Polykey agent should be capable of being a CA, since CAs are still really useful, and I want to explore how CAs can help machine security especially in the context of the Matrix OS.

**Comment by CMCDragonkai** [comment]
Renamed the title so it sounds cooler.
