### ISSUE TITLE
Use default exports for handler classes

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey#520]
### Specification

As a standard we want to use default exports if a file exports a single class. The client handlers used to export the caller and handler definition. Now it's just the handler so it needs to be updated to a default export.

### Additional context

* Related #509 
* Related #513 

### Tasks

1. update all of the client handlers to use default exports.

**Comment by tegefaulkes** [comment]
I accidentally created this to soon. let me edit it.

**Comment by tegefaulkes** [comment]
Is there any technical reason to use default exports?

I think named exports are just generally better for maintainability. They prevent renaming things when you import them. Otherwise it's possible for the imported and exported name to become out of sync.

**Comment by CMCDragonkai** [comment]
It's just convention and consistency. Actually both can be used at the same time. Sometimes I provide a default export and named exports. **But the name of the file should always be the same as the name of the default export**.

**Comment by CMCDragonkai** [comment]
See if you can do this before we extract out all the CLI to Polykey-CLI.

**Comment by CMCDragonkai** [comment]
Doing this now in #552.

**Comment by CMCDragonkai** [comment]
Doing this now in #552.

**Comment by CMCDragonkai** [comment]
I think you used suffix naming. `XHandler`. Whereas usually we prefer prefix naming. Like `EventX`, or `ErrorX`, so `HandlerX` should be used instead.

But since the entire directory is this... it could be shortened to just `X`. In this case instead of `NodesClaimsGetHandler`, it could just be `NodesClaimsGet`. Subject, object verb order.

I'm dropping the `Handler` name then.
