### ISSUE TITLE
Codegen for proto -> js

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey#58]
So I am trying to figure out the best way to compile proto files so they are resolved properly by webpack as it seems they are not handled properly. 

The best way to me looks like first compiling the proto files into javascript using `protoc` or `grpc_tools_node_protoc` (from grpc-tools).

**Comment by robert-cronin** [comment]
So the following command that works well on windows:
```
grpc_tools_node_protoc --plugin=protoc-gen-grpc=grpc_node_plugin --js_out=import_style=commonjs,binary:./proto/compiled --ts_out=./proto/compiled --grpc_out=./proto/compiled -I ./proto ./proto/*.proto
```
fails on nixos with `ENOENT` when trying to call `<rootDir>/node_modules/grpc-tools/bin/protoc`

**Comment by robert-cronin** [comment]
I have been trying to build `grpc-tools` binaries directly from [grpc-node/packages/grpc-tools](https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools) but I am getting an error of `/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/ld: cannot find -lgcc`

**Comment by CMCDragonkai** [comment]
It turns that this https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools package is just a JS shim around a native compiled C++ set of executables.

In fact it doesn't event really use `node-pre-gyp`, since that would require a `binding.gyp` file to exist.

To actually package up https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools we will need to write a C++ Nix derivation properly based on their CMake instructions and package that up, and then build a custom Nix expression for the package that actually needs to do a source patch on `package.json`. In particular it needs to change the scripts:

```
  "scripts": {
    "install": "node-pre-gyp install",
    "prepublishOnly": "git submodule update --init --recursive && node copy_well_known_protos.js"
  },
```

So it only acquires it from a pre-existing executable.

But this is not really necessary for now, it's low priority since we can use protoc from windows.

**Comment by CMCDragonkai** [comment]
Posted an upstream issue: https://github.com/NixOS/nixpkgs/issues/93173

**Comment by robert-cronin** [comment]
Closing on account of migration to gitlab
