### ISSUE TITLE
Persistence of secret vaults

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey#7]
Secret bundles will the unit of transfer in Polykey. One property of secret is that they are encrypted at rest. This is due to the fact they are containers of secrets and responsible for providing security for the secrets.

As of now secret bundle persistence will be implemented by naively serialising the secret bundle (using tar) and then encrypting it using the PGP standard.

One pitfall of this approach is that even a small change in secret bundle will mean the entire structure will reserialised. This may not be a big issue when dealing small files in small quantities, but if dealing with 1000s of secrets or large binary files, it will pose a greater issue.

Refer to <insert link> issue as a possible solution

**Comment by MeanMangosteen** [comment]
Libraries used for creating archives with node:
https://github.com/archiverjs/node-archiver
https://github.com/mafintosh/tar-stream

The latter, as the name, suggests, is a tar stream which means we can pack and unpack tar files without using the file system. Since polykey uses an in memory file system anyway, I can't see a benefit of using this.

**Comment by CMCDragonkai** [comment]
I had started on figuring out how to integrate an archive system into Polykey a while back using: https://github.com/MatrixAI/js-virtualtar

However in this process, I realise that this is the wrong model. The tar system is just not flexible enough to deal with "insertions" and "deletions" in the middle. This can happen if we are changing the value of a "key" to a different length.

That's why we need to investigate how to actually map changes to virtualfs to changes to some on-disk structure. This could potentially be done similar to hybrid data structures that support databases, possibly via memory mapping a large file block and doing disk based memory management similar to B-trees. But due to portability reasons, we may not have memory mapping available to us in Android/iOS or other platforms, so an alternative strategy could be pursued. I saw that libgit2 can be compiled without memory mapping and Git itself persists its state via object files in `.git`, I think that may be a potential strategy to do this, but we need to do more research here.

Especially with how this interacts with block ciphers.

If this synchronisation system can be implemented, it would be like FUSE but implemented in pure JS. Then the constructor of VirtualFS could have some option to state that the changes to the virtual filesystem should be persisted to disk somehow.

**Comment by MeanMangosteen** [comment]
[js-virtualtar](https://github.com/MatrixAI/js-virtualtar) allows indexing (random access) allows still suffers the problem of reserialising the entire entity on any change within the vfs. So we need a way to persist the vfs to desk, and only flush the chunks that changes were applied to. A memory mapped file could allow this--whatever changes we make to the in memory array structure will eventually be persisted to disk. Javascript doesn't natively support the mmap() syscall but we could use a c++ addon with node. But not all javascript runtimes support c++ and as of now none support a mmap() call. As a result using a native addon means Polykey cannot be cross platform as not all platforms are running node.
 
There are implementions, however, which demonstrate that is possible to synch chuncks of a data structure in memory to disk. See  

[libgit2](https://github.com/libgit2/libgit2) which offers an option to omit the use  of memmap
[fuse](https://github.com/libfuse/libfuse) and [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) - userspace file system which can also be mounted on an s3 bucket.

Along with research in to block based data structures and block ciphers needs to be done.

**Comment by MeanMangosteen** [comment]
#2 Merging into one issue.

From @CMCDragonkai 
Ideally we would want to be able to change secrets (that is write more secrets to a secret repo, remove secrets from a secret repo, or even change the size of a secret file) randomly without doing linear operations like re-encryption and re-serialisation of archive formats. This may even help secret sharing to be more efficient in the future.

- https://en.wikipedia.org/wiki/Disk_encryption_theory

Consider existing secret database tech like sqlite.

http://www.ciphersbyritter.com/NEWS4/ECBMODE.HTM

These 2 projects use FUSE to mediate between a filesystem in userspace and encrypted backend on disk somewhere. FUSE is interesting because we can offer a standard FS interface to consumers of Polykey secrets. But to be really secure you would have to either use mount namespaces or file descriptors as capabilities to allow specific processes to access secrets.

- https://nuetzlich.net/gocryptfs/comparison/
- https://github.com/timbod7/secretfs

FUSE is not portable to mobile devices.

**Comment by CMCDragonkai** [comment]
BaseX is a XML database https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/data/DiskData.java

This means basex basically manages synchronisation from a "tree-like" representation on the client side and is able to make changes to that tree and persist those changes to disk.

I played around with the database before, and I think it sort of had not great performance with incremental updates to the XML tree.

I wrote some questions and discussed this with the author here: https://github.com/BaseXdb/basex/issues/1529

But the Java code here: https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/data/DiskData.java is where it deals with disk persistence.
this may be useful for figuring out how to persist data from our virtualfs and on-disk structure

**Comment by MeanMangosteen** [comment]
One way to address to achieve encryption at rest is to use [Stacked filesystem encryption]https://wiki.archlinux.org/index.php/disk_encryption#Stacked_filesystem_encryption) this would work by mounting the native host fs to a second pseudo-fs (vfs) which would be responsible for [en|de]cryption of secrets (to be confirmed). 


Implemenations of stacked fs:
[encryptfs](https://wiki.archlinux.org/index.php/ECryptfs)
[encfs](https://wiki.archlinux.org/index.php/EncFS)

Also look into hdf5 file format. Used for data science, it loads a file into memory where is expands into a fs.

**Comment by MeanMangosteen** [comment]
Previously it was mentioned that we can create a memory mapped file to represent the file system that is the secret bundle. After investigating into ecryptfs and encfs, having an openly visible directory structure is also a viable solution. Both systems utilise the underlying filesystem to maps the contents of an unencrypted directory (known as the upper directory) encrypts it and stores it to a directory on disk (known as lower directory). For example, with the default behaviour of ecryptfs, any changes flushed to the ~/Private (upper) will result in those changes encrypted and persisted to  the ~/.Private (lower). The directory structure, permissions, and approximate file sizes are visible in the lower directory but the contents of the files are cipher text. The upper directory is a mountpoint on the filesystem, so mounted/unmounted as per the users' desires.

A similar approach can be applied to the Polykey system. The upper directory in this case will be completely in memory by utilising vfs. As the Polykey process makes changes in the upper directory, they are first encrypted, through an extension of vfs, then persisted on disk. In doing this, the only time there is exists an upper directory is when the Polykey application commands it, it can never be visible to any other process. Another point to note, is that [en|de]cryption occurs 'on-the-fly'. That is to say that the entire lower directory is not decrypted and loaded in to the upper directory whenever Polykey is active. Only the chunks are currently being read/written to are in the upper, in memory, directory. This is possible because encfs supports random access of encrypted files.

**Comment by CMCDragonkai** [comment]
Whether chunks are encrypted/decrypted vs whether a file is encrypted/decrypted as a unit depends on whether they are using stream encryption/decryption. Doing this should allow some extent of random access within a file. If not, that adds complications to when you create a file descriptor to a file, and write chunks to that file descriptor, does the system buffer up these chunks before fully encrypting them in one go, or does it encrypt chunk by chunk?

There can definitely be some slowdowns. Like if I open a fd to a file, and then seek to the middle, and start overwriting bytes from that point on wards. The most efficient would be to consider the encrypted "lower" directory as chunks, and start re-encrypting chunks from nearest chunk boundary onwards. But it could be that the system EncFS or EcryptFS just re-encrypts the entire file. We don't know yet, will need to examine more of it.

> eCryptfs is derived from Erez Zadok's Cryptfs.[4] It uses a variant of the OpenPGP file format for encrypted data, extended to allow random access, storing cryptographic metadata (including a per-file randomly generated session key) with each individual file.[2]
> https://en.wikipedia.org/wiki/ECryptfs

I see that the wikipedia page does explicitly mention that random access is supported in encrypted files.

Anyway, the point is that we can do something similar, but with VirtualFS acting as the upper directory, and the lower directory being some directory that exists on the host OS. In the future, that lower directory itself can be further mediated directly into some memory mapped file so that way a Polykey "database" file is just a single file instead of a directory. But that's not needed at the moment. **However doing this will get around the filename limit issue.** Because ecryptfs and encfs relies on the underlying filesystem to do this, and it encrypts the filename itself, we have limits on how long the filename can be (more limited than the standard 255 characters).

So we need to figure out how to adapt VirtualFS into a stackable filesystem so we can have VirtualFS acting as the upper directory.

**Comment by CMCDragonkai** [comment]
Note that in order to use ecryptfs on NixOS. You need to use `security.pam.enableEcryptfs = true;` in configuration.nix. You then need to activate the kernel module using `modprobe ecryptfs` or you can specify it in the configuration.nix as well. Then you need the `ecryptfs` package: `nix-env -i ecryptfs`. Then you run:

```
ecryptfs-setup-private --nopwcheck --noautomount
ecryptfs-mount-private
ecryptfs-umount-private
```

To remove everything delete `~/.ecryptfs`, `~/Private`, `~/.Private`. That's it. The ecryptfs source code is pretty old and it appears to rely on the kernel, whereas nowadays I'd believe something like this would instead be done via FUSE instead of being part of the kernel directly. It also is quite complicated to use outside of mounting just `~/Private` and `~/.Private`. Note that `~/Private` is a mountpoint, whereas the `~/.Private` isn't.

**Comment by CMCDragonkai** [comment]
Note that if we are intending to write our own block store, we should be able to build on top of library-databases like leveldb, rocksdb or lmdb... etc. Either that or we piggy back off IPFS block service and their repo spec: https://github.com/ipfs/js-ipfs-block-service Might need to dive into FUSE to learn more about this. I think should be split off into a separate issue however and be something we want to address after we get the upper and lower directory feature into our Polykey persistence.

Also: https://github.com/greglook/blocks and https://github.com/IAIK/secure-block-device

**Comment by MeanMangosteen** [comment]
Previously it had been decided secret bundle, now known as a secret vault, had a single vault key to encrypt all files in the bundle. This would use symmetric block ciphering such as AES. Since streaming i/o or ability to handle unknown data sizes are desirable, and a block cipher is not able to provide these properties, a stream cipher can be used. AES in CTR mode achieves the above properties as well as being parallelisation in encryption as well as decryption. It also support random access. Thus is an ideal candidate. 

With any stream cipher, it is susceptible to the [two time pad attack](https://crypto.stackexchange.com/questions/59/taking-advantage-of-one-time-pad-key-reuse). This means we cannot have a single vault key for lower directory content encryption. Each time a file is encryption a new key will have to be generated. This can be done by still having a vault key from which each of the file keys is dervided. A key dervivation function such as PBKDF2 can be used where the password is the vault key. The salt can be static, such as the filename. Since we are not using a dictionary word password, a random salt is not important. 

The filenames may also be encrypted, but not using a stream cipher. A standard block cipher will be used for reasons important described later.

When transporting a vault to another keynode. They vault key can be will be encrypted only with two public keys, the vault owner and the recipient's. This way the recipient can decrypt the vault key and deterministically generate the individual file keys. The vault is a standard symmertric block cipher so the filenames can be decrypted and used as salt.

**Comment by ll-aashwin-ll** [comment]
> Previously it had been decided secret bundle, now known as a secret vault, had a single vault key to encrypt all files in the bundle. This would use symmetric block ciphering such as AES. Since streaming i/o or ability to handle unknown data sizes are desirable, and a block cipher is not able to provide these properties, a stream cipher can be used. AES in CTR mode achieves the above properties as well as being parallelisation in encryption as well as decryption. It also support random access. Thus is an ideal candidate.
> 
> With any stream cipher, it is susceptible to the [two time pad attack](https://crypto.stackexchange.com/questions/59/taking-advantage-of-one-time-pad-key-reuse). This means we cannot have a single vault key for lower directory content encryption. Each time a file is encryption a new key will have to be generated. This can be done by still having a vault key from which each of the file keys is dervided. A key dervivation function such as PBKDF2 can be used where the password is the vault key. The salt can be static, such as the filename. Since we are not using a dictionary word password, a random salt is not important.
> 
> The filenames may also be encrypted, but not using a stream cipher. A standard block cipher will be used for reasons important described later.
> 
> When transporting a vault to another keynode. They vault key can be will be encrypted only with two public keys, the vault owner and the recipient's. This way the recipient can decrypt the vault key and deterministically generate the individual file keys. The vault is a standard symmertric block cipher so the filenames can be decrypted and used as salt.

**Comment by MeanMangosteen** [comment]
References:
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

https://en.wikipedia.org/wiki/PBKDF2
https://www.npmjs.com/package/pbkdf2

https://github.com/ricmoo/aes-js

**Comment by CMCDragonkai** [comment]
The salt for PBKDF2 would have to be the full path including the encrypted name of the file, not the plaintext of the file. So the file name would have to be separately encrypted.

The vault key is still symmetric. The basic idea is that anyone who has the plaintext vault key, along with the filename can then proceed to acquire a "file key" and use that to subsequently stream/block decrypt the actual cipher text file.

Also CTR mode can be parallelised which can be useful later.

I think this design should work even if we were to swap out the lower directory for a real filesystem-file.

**Comment by CMCDragonkai** [comment]
Hey @ll-aashwin-ll can you paste that link where it had the visual display of the vulnerability of using the same key for CTR stream cipher, I think that would be a good reference.

**Comment by MeanMangosteen** [comment]
> Hey @ll-aashwin-ll can you paste that link where it had the visual display of the vulnerability of using the same key for CTR stream cipher, I think that would be a good reference.

https://crypto.stackexchange.com/questions/59/taking-advantage-of-one-time-pad-key-reuse

**Comment by MeanMangosteen** [comment]
CTR mode is not safe for disk encryption.
See: https://en.wikipedia.org/wiki/Disk_encryption_theory#Problem_definition
XTS mode seems to be a suitable choice instead. It allows random reads/writes.

**Comment by MeanMangosteen** [comment]
There is no longer a single, overaching vault key. Each keynode maintains their own vault key (for any particular vault). See #13 .

Also XTR does not seem suitable. See encfs audit: https://defuse.ca/audits/encfs.htm.

CBC appears to be a better option. Block-level encryption can still be achieved, although with some overhead. See Encfs docs on how they do this for inspiration.

**Comment by MeanMangosteen** [comment]
GCM is being used. Modern userspace encrypted filesystem are using this: [gocryptfs](https://nuetzlich.net/gocryptfs/forward_mode_crypto/), [CryFS](https://www.cryfs.org/howitworks).

[gcm wiki.](https://en.wikipedia.org/wiki/Galois/Counter_Mode)

It is efficient, provides data authentication and is parallelisable .
