### ISSUE TITLE
Synchronous vs Asynchronous API

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#9]
The JS that we write can be written synchronous style or asynchronous style.

When interacting with virtualfs, the easiest to use is simply the synchronous system, since there's no IO and so there's no need to wait on anything.

However for the EncryptedFS we will need to perform IO to write the file to disk. Which means if we used synchronous style, it will block the entire JS runtime. This may be complicated if the UI system is running against the same loop.

Which isn't a problem for CLI applications most of the time. And even for things like Electron/React Native/NativeScript, there's a separate UI loop compared to the backend code.

So we may get away with writing it all synchronous. But it's probably a good idea to think about how to use asynchronous, or support both APIs just like how js-virtualfs exposes both async and sync APIs.

**Comment by CMCDragonkai** [comment]
It would be a problem for web browsers, but at this moment I don't think Polykey would run in the browser due to other limitations as well. Lack of persistence is one issue. But we may investigate browser based systems that could expose a limited subset of the FS API. But that's for a later concern.

**Comment by CMCDragonkai** [comment]
I'm using the kbpgp for key generation right now. I've noticed it uses an asynchronous API (callback pattern).

We will probably convert this to a promise based async/await: https://gist.github.com/samtgarson/3f4fd3ea3485b0db4894a99bc1c8e186 (this shows how to do it with kbpgp).

In JS it is not possible to convert async API into sync API: https://stackoverflow.com/a/29440696/582917

This is why it's usually better to start with an sync API and offer async wrappers around it, like `js-virtualfs`. In JS, once async always async and it infects the rest of the program.

In other languages like Python, it is possible to convert async to sync, just by doing a blocking loop call that checks if the async result is available. You have to yield back to the Python scheduler at each step using sleep of 0 seconds. You have something similar in Javascript with `setTimeout`: https://stackoverflow.com/a/779785/582917 But we cannot use it here, because the yield itself only works asynchronously as well, thus we don't end up converting it to be synchronous.

**Comment by CMCDragonkai** [comment]
We should begin converting them to async/await pattern as we are using these libraries @ll-aashwin-ll. This will make our codebase more consistent.

**Comment by MeanMangosteen** [comment]
Since encryptedfs will have to preserve nodefs's api so that it can be used in its place, the traditional callback style for async methods will be used, along with sync methods. 

A separate module for promisified methods can be made just like nodefs. But since nodefs's promise module is still in an experimental status and not widely adopted, priority should be given to development of the above.

**Comment by MeanMangosteen** [comment]
> This is why it's usually better to start with an sync API and offer async wrappers around it, like js-virtualfs. In JS, once async always async and it infects the rest of the program.

As discussed in #18 we cannot do it this way because the because 'async' wrapper around sync will the method will be scheduled for execution asynchronously, but it execution itself will still block. Hence we will be using native async calls for efs. 

Since the Polykey api does not have to preserve any existing API method signatures, like efs does with fs, it can use modern promise primitives for async methods instead of callbacks. 

I think we can reference this issue in #3 and [EncryptedFS implementation](https://github.com/MatrixAI/js-virtualfs/issues/7) and close it. @CMCDragonkai ?
