### ISSUE TITLE
Optimizing IPC communication between agent and client (CLI/GUI)

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey#90]
At the moment, the IPC communication is "bulky" (and not efficient?) and is not using a standard RPC system.

If we change the communication between Agent and Client to gRPC, we have to beware of the security implications: https://github.com/MatrixAI/js-polykey/issues/50#issuecomment-677600761 (basically we have to use mTLS to secure it).

The advantage is that clients can then be operating over the network as well.

**Comment by CMCDragonkai** [comment]
Also: https://security.stackexchange.com/questions/176319/what-is-the-most-secure-way-of-transferring-a-secret-between-2-processes-running

The agent will be listening for clients.

Any process can try to establish connection to the agent. But only legitimate clients can connect.

How are legitimate clients identified? It seems like the master pub/priv keypair will need to be used, and then an established communication using a token. Basically a persistent connection for the GUI.

However for CLI this gets complicated, as that mean that the user has to keep authenticating each time. And the whole point of having a running keynode separate from the client is to avoid having to authenticate all the time.

**Comment by CMCDragonkai** [comment]
At any case, we have to establish a proper protocol for authenticating clients to the agent. And these clients have full control over the agent. And then figure out how CLI programs can "authenticate" to the client and stay authenticated. We could use a JWT as a token the client saves in its temporary directory which is only readable/writable by the user. This would be sufficient. And the JWT has a built-in expiry.

**Comment by robert-cronin** [comment]
I should probably explain what I meant by bulky. For any solution that uses gRPC, one only needs to specify a service and the rpc signatures within the proto files and the rest is taken care of (i.e. gPRC/HTTP2 will automatically route each method call to the right place on the server and make sure no packets get mixed between subsequent calls of the same function)

Since gRPC in nodejs doesn't support UDS, we have had to basically replicate this functionality ourselves by defining a MessageType like `GET_SECRET` or `CREATE_VAULT`. We also have to serialize/deserialize messages which is something gRPC does automatically. Another thing that makes our code bulky is the managing sockets directly which includes managing life cycle of the sockets, reading data, stitching together packets, and handling socket errors

All of this leads to a fairly hefty agent code, which is "bulky" with respect to a gRPC based implementation.

**Comment by robert-cronin** [comment]
so from [this discussion](https://github.com/MatrixAI/js-polykey/pull/84#discussion_r486275119), one way to do this is to have teh agent/client communications over the local network and have a token based access like OAuth2.0 for the client which means the client needs to hold state.

**Comment by robert-cronin** [comment]
Eventually we should have one `grpc.Server` and that can add multiple services like `PeerService` and `AgentService`.

**Comment by robert-cronin** [comment]
There was also some discussion on having a single agent managing a single polykey instance. At first, I thought this wasn't the right way to go since the way have it now is a single agent per user and only has one socket and is fairly scalable to many nodes on a single computer. This might in fact be the way to go but we will have to discuss these tradeoffs.

As for the 1 to 1 approach, if the agent is more tightly coupled to the single gRPC server as discussed above, we could eliminate a whole bunch of logic for managing pk instances.

**Comment by CMCDragonkai** [comment]
Yes I think 1 agent to 1 PK store. Different PK stores are meant to have 
different agents.

Also you actually can have different sockets, since its all over 
localhost with different ports. With UDS its just different socket 
paths. Totally fine.

**Comment by robert-cronin** [comment]
there is also an issue of discovery, lets say a client wants access to node path `~/SomePKState`, then how does it find out that its served on port `28473`? Perhaps one way to do it is to actually have the discovery over that UDS port. This way the 'authorisation' server that is used in OAuth2.0 could also be done via this UDS port.

**Comment by CMCDragonkai** [comment]
If you're talking about client to agent:

Client's shouldn't be specifying the the node path. They have no 
knowledge of that unless they themselves are starting it.

Also you can put a temporary port/pid lockfiles in the pkstate 
directories. You can see this as `x.pid` files but also these files 
might then store the PID, or the port that it is bound to.

If you're talking about p2p discovery then...

IPv4 multicast addresses for local network discovery. Also I think ipv6 
too. But also most keynodes should be using a default port.

Note that multicast as we know doesn't work across WAN cause ISPs don't 
route those packets. But that's why this P2P system requires a different 
way when going over WAN.

**Comment by robert-cronin** [comment]
yeah that might be a better idea, I hadn't thought to use the actual node path, which both client and agent know about, as a discovery mechanism for which port it is served over.

At them moment the default port is stored as a part of the peer info in the polykey state folders, in case it doesn't exists yet it will autofind a port unless a port is set with the environment variable `PK_PORT`

**Comment by robert-cronin** [comment]
This is already fixed I think, but I will confirm and close in the upcoming PR
